# Generated by Django 4.0.6 on 2022-07-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
