# Generated by Django 4.0.6 on 2022-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='URL изображения'),
        ),
    ]
