# Generated by Django 4.0.6 on 2022-07-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
    ]
